PERCEPCIONES = {
    'SUELDO',
    'VACACIONES',
    'FONDO DE AHORRO EMPRESA',
    'PRIMA VACACIONAL GRAV',
    'PRIMA VACACIONAL EXEN',
    'PTU GRAV',
    'PTU EXENT',
    'AGUINALDO GRAVADO',
    'AGUINALDO EXENTO'
}

DEDUCCIONES = {
    'ISR',
    'FONDO DE AHORRO EMPRESA',
    'FONDO DE AHORROX',
    'ISR REGLAMENTO'
}